sudo: required
services:
  - docker

before_install:
  - docker build -t kristinnv12/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true kristinnv12/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-137816445228"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY